### ISSUE TITLE
Top 2 rows flicker

### ISSUE THREAD

**Issue by supercrab** [emgoz/HUB08SPI#1]
Great library!  I've wired up the 64x16 display and everything compiles and runs fine.  On my display the top row flickers a faint red when a pixel is off and on the second row pixels that are on flicker off.  As the pixel count increases so does the flickering.

**Comment by emgoz** [comment]
As the library treats every line the same, I don't think it is a software problem. Maybe it's some kind of interfrence on the data lines, most likely caused by long cables with high capacitve coupling. Try using a shorter ribbon cable and not a breadboard between the microcontroller and the display, it has a large capacitance. Keep in mind that the SCK frequency is 4 MHz default, that's a lot for long connections.
Additionally, your power supply might be too weak (I hope your already using an external power supply. The display "works" without and draws power from the data lines, but that is an unwanted, ver ugly effect that might even damage the microcontroller.).

**Comment by supercrab** [comment]
i'm using short 10 cm wires directly connected to my arduino clone and the 5v is powered with a wall power supply.  I shall using a different arduino and a larger power supply and see if that helps.  I've controlled other bi-colour led matrices OK.  I'll report back!

**Comment by supercrab** [comment]
I've tried a 3 amp power supply but no change in the flicker.  Weird!

**Comment by supercrab** [comment]
Boom!  I fixed it! :dancer: 

I had to connect my GND on the display to my arduino GND! :100:
