### ISSUE TITLE
Display redraws slowly on ATMEGA1284

### ISSUE THREAD

**Issue by supercrab** [emgoz/HUB08SPI#2]
The code works perfectly on ATMega328.  I decided to use an ATMEGA1284 for more RAM but the display appear3e to run extremely slow.   I then altered the code to use PORTA insead of PORTD (to avoid clashing with the timerOne pins) but it didn't seem to help.   Is there anything else I can try?

**Comment by emgoz** [comment]
I assume the problem is the PMW state detction in the scan() function. I built it so that the display is only refreshed in the "off"-state of the enable pin. This way artefacts of half drawn lines are prohibited. The following two lines in the code achieve that (blocking while loop):

> uint16_t r = -2000;  //timeout
>  while (!(PIND & (1<<3)) && ++r);

To fix the problem when you are using a different PWM source than pin D3, change the "PIND & (1<<3)" to the real PWM-pin you use. Make sure that the PWM-frequency is at high enough to avoid flickering. If you don't care about the artefacts, you can either set r = -1 instead of -2000 or remove the two lines entirely.

Hope that helps.

**Comment by supercrab** [comment]
Brilliant!  I shall give that a test when I get back to the lab!
Once I've fixed this, I hope to include the changes into the main library to make this library compatible with other chips!

Thanks!

**Comment by supercrab** [comment]
It works like a charm!

Thanks!
